#include "gtest/gtest.h"

#include "../day.h"

// These tests are automatically generated by ChatGPT. (Had to help with some timezones and unix time_t conversions)


TEST(UTCTimeTest, IncrementSecondsCopy)
{
    UTCTime t1(1620225000); // 05/05/2021 @ 2:30pm (UTC)
    UTCTime t2 = t1.IncrementSecondsCopy(60);
    EXPECT_EQ(t2.AsUTCTimeT(), 1620225060); // 05/05/2021 @ 2:31pm (UTC)
}

TEST(UTCTimeTest, IncrementNorwegianDaysCopy)
{
    UTCTime t1(1620225000); // 05/05/2021 @ 2:30pm (UTC)
    UTCTime t2 = t1.IncrementNorwegianDaysCopy(1);
    EXPECT_EQ(t2.AsUTCTimeT(), 1620311400); // 05/06/2021 @ 2:30pm (UTC)
}

TEST(UTCTimeTest, AsNorwegianDay)
{
    UTCTime t1(1620225000); // 05/05/2021 @ 2:30pm (UTC)
    NorwegianDay d = t1.AsNorwegianDay();
    EXPECT_EQ(d.GetDay(), 5);
    EXPECT_EQ(d.GetMonth(), 5);
    EXPECT_EQ(d.GetYear(), 2021);
}

TEST(UTCTimeTest, AsNorwegianTime)
{
    UTCTime t1(1620225000); // 05/05/2021 @ 2:30pm (UTC)
    NorwegianTime nt = t1.AsNorwegianTime();
    EXPECT_EQ(nt.GetHour(), 16);
    EXPECT_EQ(nt.GetMinute(), 30);
    EXPECT_EQ(nt.GetSecond(), 0);
}

TEST(UTCTimeTest, DaylightSavingStart)
{
    UTCTime t1(1616259600); // 03/20/2021 @ 5:00pm (UTC)
    UTCTime t2 = t1.DaylightSavingStart();
    EXPECT_EQ(t2.AsUTCTimeT(), 1616893200); // 03/28/2021 @ 3:00am (UTC+2)
}

TEST(UTCTimeTest, DaylightSavingEnd)
{
    UTCTime t1(1636183200); // 11/06/2021 @ 7:20am (UTC)
    UTCTime t2 = t1.DaylightSavingEnd();
    EXPECT_EQ(t2.AsUTCTimeT(), 1635642000); // 31/10/2021 @ 2:00am (UTC+1)
}
